services:
  users:
    url: http://localhost:9001

  orders:
    url: http://localhost:9002

  payments:
    url: http://localhost:9003

routes:
  - path: /users
    service: users

  - path: /orders
    service: orders
  
  - path: /payments
    service: payments